[control]
34.242.186.67 ansible_user=ubuntu node_name=control

[workers]
3.249.49.60 ansible_user=ubuntu node_name=worker-1
34.241.227.64 ansible_user=ubuntu node_name=worker-2

[k3s_cluster:children]
control
workers